"""Part 4: Visualizations, individual tests, quantile results, author, references, footer"""

VISUALIZATIONS = """
<section id="visualizations">
<div class="container">
  <h2 class="section-title">📊 Visualizations</h2>
  <p class="section-subtitle">Publication-quality plots generated by the library.</p>

  <div class="fig-container">
    <img src="img/cell_05.png" alt="Time Series Data">
    <p class="fig-caption">Figure 4: Financial Time Series — EUR/USD, Gold, and Crude Oil WTI daily data</p>
  </div>
  <div class="fig-container">
    <img src="img/cell_09.png" alt="Fourier Fit">
    <p class="fig-caption">Figure 5: Fourier Approximation — Optimal frequency fit capturing structural breaks in EUR/USD</p>
  </div>
  <div class="fig-container">
    <img src="img/cell_26.png" alt="QR-KSS Quantile Profile">
    <p class="fig-caption">Figure 6: QR-KSS Quantile Profile — Test statistics across τ ∈ {0.1, ..., 0.9}</p>
  </div>
  <div class="fig-container">
    <img src="img/cell_29.png" alt="QR-Fourier-KSS Profile">
    <p class="fig-caption">Figure 7: QR-Fourier-KSS Quantile Profile — One-step Fourier quantile regression</p>
  </div>
</div>
</section>
"""

TESTS_DETAIL = """
<section id="tests">
<div class="container">
  <h2 class="section-title">🔍 Individual Test Results</h2>
  <p class="section-subtitle">Detailed output from each test on the EUR/USD exchange rate series.</p>

  <div class="test-detail">
    <h4>1. KSS — Kapetanios, Shin &amp; Snell (2003)</h4>
    <p class="ref">ESTAR nonlinearity under demeaned/detrended series</p>
    <pre>Test Statistic:  -2.9962    Model: Intercept + Trend
Optimal k: 0    Optimal Lag: 0
CV 1%: -3.770  |  No       CV 5%: -3.090  |  No
CV 10%: -2.770  |  Yes *</pre>
  </div>

  <div class="test-detail">
    <h4>2. Fourier-KSS — Christopoulos &amp; León-Ledesma (2010)</h4>
    <p class="ref">Fourier detrending + ESTAR nonlinearity</p>
    <pre>Test Statistic:  -3.4528    Model: Intercept
Optimal k: 1.0    Optimal Lag: 0
CV 1%: -4.350  |  No       CV 5%: -3.550  |  No
CV 10%: -3.170  |  Yes *
F-stat (Fourier): 123.2801  F critical (5%): 4.929</pre>
  </div>

  <div class="test-detail">
    <h4>3. Fourier-ADF — Enders &amp; Lee (2012)</h4>
    <p class="ref">Linear ADF with Fourier structural breaks</p>
    <pre>Test Statistic:  -4.2818    Model: Intercept
Optimal k: 1.0    Optimal Lag: 0
CV 1%: -4.420  |  No       CV 5%: -3.810  |  Yes *
CV 10%: -3.490  |  Yes *
F-stat (Fourier): 123.2801  F critical (5%): 4.929</pre>
  </div>

  <div class="test-detail">
    <h4>4. Fourier-KSS Bootstrap — Christopoulos &amp; León-Ledesma (2010)</h4>
    <p class="ref">Sieve bootstrap critical values (500 replications)</p>
    <pre>Test Statistic:  -3.4528    Model: Intercept
Optimal k: 1.0    Optimal Lag: 0
Bootstrap CV 1%: -4.152  |  No   CV 5%: -3.541  |  No
CV 10%: -3.198  |  Yes *</pre>
  </div>

  <div class="test-detail">
    <h4>5. Fourier-Kruse — Güriş (2019)</h4>
    <p class="ref">ESTAR with non-zero threshold c ≠ 0</p>
    <pre>Test Statistic (τ):  18.5061    Model: Intercept
Optimal k: 1.0    Optimal Lag: 0
CV 1%: 18.820  |  No       CV 5%: 14.800  |  Yes *
CV 10%: 12.520  |  Yes *</pre>
  </div>

  <div class="test-detail">
    <h4>6. FFKRUSE — Biyikli &amp; Hepsağ (2025)</h4>
    <p class="ref">Fractional frequency Fourier-Kruse extension</p>
    <pre>Test Statistic (τ):  22.4471    Model: Intercept
Optimal k: 1.1    Optimal Lag: 0
CV 1%: 19.560  |  Yes *    CV 5%: 14.860  |  Yes *
CV 10%: 12.700  |  Yes *</pre>
  </div>

  <div class="test-detail">
    <h4>7. Fourier-Sollis — Ranjbar et al. (2018)</h4>
    <p class="ref">AESTAR asymmetric nonlinearity + Fourier breaks</p>
    <pre>Test Statistic (F):  9.5171    Model: Intercept
Optimal k: 1.0    Optimal Lag: 0
CV 1%: 9.780  |  No        CV 5%: 7.472  |  Yes *
CV 10%: 6.395  |  Yes *</pre>
  </div>

  <div class="test-detail">
    <h4>8. FFSOLLIS — Biyikli &amp; Hepsağ (2025)</h4>
    <p class="ref">Fractional frequency Fourier-Sollis</p>
    <pre>Test Statistic (F):  10.7636    Model: Intercept
Optimal k: 1.1    Optimal Lag: 0
CV 1%: 10.165  |  Yes *    CV 5%: 7.910  |  Yes *
CV 10%: 6.871  |  Yes *</pre>
  </div>

  <div class="test-detail">
    <h4>9. Fourier-Sollis Zero-Mean — Hepkorucu &amp; Çınar (2021)</h4>
    <p class="ref">Zero-mean model for transformed series</p>
    <pre>Test Statistic (F):  9.5171    Model: Zero-Mean
Optimal k: 1.0    Optimal Lag: 0
CV 1%: 9.767  |  No        CV 5%: 7.472  |  Yes *
CV 10%: 6.391  |  Yes *</pre>
  </div>

  <div class="test-detail">
    <h4>10. QR-KSS — Li &amp; Park (2018)</h4>
    <p class="ref">Quantile regression nonlinear unit root</p>
    <pre>Quantile    t_T(τ)      CV 5%     Reject
τ=0.1     -53.1977    -2.1719     Yes
τ=0.2     -45.3189    -2.3574     Yes
τ=0.3     -38.5869    -2.3587     Yes
τ=0.5     -34.4442    -2.3716     Yes
τ=0.7     -50.9785    -2.3511     Yes
τ=0.9    -109.0470    -2.2763     Yes</pre>
  </div>

  <div class="test-detail">
    <h4>11. QR-Fourier-KSS — Bahmani-Oskooee et al. (2020)</h4>
    <p class="ref">One-step quantile regression with Fourier terms</p>
    <pre>QKS statistic: 107.194    QCM statistic: 221847.9
Bootstrap CV: computed via sieve bootstrap under H₀</pre>
  </div>

  <div class="test-detail">
    <h4>12. KSS-FF — Omay, Corakci &amp; Hasdemir (2021)</h4>
    <p class="ref">Fractional Fourier function restoring Taylor expansion residuals</p>
    <pre>Test Statistic:  -4.3171    Model: Intercept
Optimal k: 1.1 (fractional)    Optimal Lag: 0
CV 1%: -4.103  |  Yes *    CV 5%: -3.522  |  Yes *
CV 10%: -3.212  |  Yes *</pre>
  </div>

  <div class="test-detail">
    <h4>13. FWKSS — Haar Wavelet + Fourier-KSS</h4>
    <p class="ref">Wavelet denoising followed by Fourier-KSS testing</p>
    <pre>Test Statistic:  -2.6440    Model: Intercept
Optimal k: 1.0    Optimal Lag: 0
CV 1%: -4.350  |  No       CV 5%: -3.550  |  No
CV 10%: -3.170  |  No</pre>
  </div>
</div>
</section>
"""

AUTHOR_REFS_FOOTER = """
<section id="author">
<div class="container">
  <h2 class="section-title">👤 Author</h2>
  <div class="author-card">
    <div class="author-avatar">MR</div>
    <div class="author-info">
      <h3>Dr. Merwan Roudane</h3>
      <p>Researcher in Econometrics &amp; Time Series Analysis. Developer of specialized Python libraries for nonlinear unit root testing, quantile regression, and wavelet-based econometric methods.</p>
      <div class="author-links">
        <a href="mailto:merwanroudane920@gmail.com">📧 merwanroudane920@gmail.com</a>
        <a href="https://github.com/merwanroudane" target="_blank">🔗 GitHub Profile</a>
        <a href="https://github.com/merwanroudane/hybridnonlinur" target="_blank">📂 Repository</a>
        <a href="https://pypi.org/project/hybridnonlinur/" target="_blank">📦 PyPI Package</a>
      </div>
    </div>
  </div>
</div>
</section>

<section id="references">
<div class="container">
  <h2 class="section-title">📚 References</h2>
  <p class="section-subtitle">Published papers and GAUSS source code underlying each test.</p>
  <ol class="ref-list">
    <li>Kapetanios, G., Shin, Y. &amp; Snell, A. (2003). Testing for a unit root in the nonlinear STAR framework. <em>J. Econometrics</em>, 112(2), 359–379.</li>
    <li>Christopoulos, D.K. &amp; León-Ledesma, M.A. (2010). Smooth breaks and non-linear mean reversion. <em>J. Int. Money Finance</em>, 29(6), 1076–1093.</li>
    <li>Enders, W. &amp; Lee, J. (2012). A unit root test using a Fourier series. <em>J. Time Series Analysis</em>, 33(5), 728–743.</li>
    <li>Kruse, R. (2011). A new unit root test against ESTAR. <em>Statistical Papers</em>, 52(1), 71–85.</li>
    <li>Sollis, R. (2009). A simple unit root test against AESTAR. <em>Economic Modelling</em>, 26(1), 118–125.</li>
    <li>Becker, R., Enders, W. &amp; Lee, J. (2006). A stationarity test with an unknown number of breaks. <em>J. Time Series Analysis</em>, 27(3), 381–409.</li>
    <li>Güriş, B. (2019). A new nonlinear unit root test with Fourier function. <em>Comm. Stat. Simul. Comput.</em>, 48(10), 3056–3062.</li>
    <li>Ranjbar, O., Chang, T., Elmi, Z. &amp; Lee, C.-C. (2018). A new unit root test against asymmetric ESTAR. <em>Iranian Economic Review</em>, 22(1), 51–62.</li>
    <li>Li, H. &amp; Park, S.Y. (2018). Testing for a unit root in a nonlinear quantile framework. <em>Econometric Reviews</em>, 37(8), 867–892.</li>
    <li>Bahmani-Oskooee, M. et al. (2020). Fourier nonlinear quantile unit root test. <em>Bull. Econ. Research</em>, 72(1), 14–33.</li>
    <li>Hepkorucu, A. &amp; Çınar, M. (2021). Testing the power properties of Fourier-Sollis under zero-mean. <em>KOCATEPEİİBFD</em>, 23(2), 171–181.</li>
    <li>Omay, T., Corakci, A. &amp; Hasdemir, E. (2021). High persistence and nonlinear behavior: unit root testing in the ESTAR framework. <em>Mathematics</em>, 9(20), 2534.</li>
    <li>Biyikli, S.İ. &amp; Hepsağ, A. (2025). New nonlinear unit root tests based on fractional frequency Fourier functions. <em>Comm. Stat. Simul. Comput.</em></li>
  </ol>
</div>
</section>

<section id="citation">
<div class="container">
  <h2 class="section-title">📝 Citation</h2>
  <div class="install-box" style="font-size:0.82rem;">
@software{roudane2026hybridnonlinur,
  author = {Roudane, Merwan},
  title  = {hybridnonlinur: Nonlinear Hybrid Unit Root Tests in Python},
  year   = {2026},
  url    = {https://github.com/merwanroudane/hybridnonlinur}
}</div>
</div>
</section>

<footer>
  <div class="container">
    <p style="font-size:1.1rem;font-weight:600;margin-bottom:0.5rem;">hybridnonlinur</p>
    <p>Nonlinear Hybrid Unit Root Tests — v1.0.0</p>
    <p style="margin-top:0.75rem;">
      <a href="https://github.com/merwanroudane/hybridnonlinur">GitHub</a> &nbsp;·&nbsp;
      <a href="https://pypi.org/project/hybridnonlinur/">PyPI</a> &nbsp;·&nbsp;
      <a href="mailto:merwanroudane920@gmail.com">Contact</a>
    </p>
    <p style="margin-top:1rem;font-size:0.82rem;">© 2026 Dr. Merwan Roudane — MIT License</p>
  </div>
</footer>
</body>
</html>
"""

with open('docs/_part4.html', 'w', encoding='utf-8') as f:
    f.write(VISUALIZATIONS + TESTS_DETAIL + AUTHOR_REFS_FOOTER)
print("Part 4 written: docs/_part4.html")
